#ifndef _STC_UART_H_11_08_30_
#define _STC_UART_H_11_08_30_

#define BUAD_RATE	9600
#define BRT_INI		(256-FOSC/16/BUAD_RATE)
//#define BRT_INI		(256-FOSC/16/12/BUAD_RATE)

#define UART_HEAD	0XFF
#define UART_TAIL	(UART_HEAD-1)
#define UART_SYN	(UART_TAIL-1)

/*#define UART_UNPACK_STATE_IDLE		0
#define UART_UNPACK_STATE_BEGIN		(UART_UNPACK_STATE_IDLE	+1)
#define UART_UNPACK_STATE_SYN		(UART_UNPACK_STATE_BEGIN+1)
#define UART_UNPACK_STATE_GET		(UART_UNPACK_STATE_SYN	+1)
#define UART_UNPACK_STATE_END		(UART_UNPACK_STATE_GET	+1)	*/

#define T1BUF_MAX_LEN	30
#define R1BUF_MAX_LEN	30
#define T2BUF_MAX_LEN	30
#define R2BUF_MAX_LEN	30

/*
#define UART_CMD_NAK			0X00
#define UART_CMD_ACK			0X01

#define UART_CMD_KEY_DOWN		0x01
#define UART_CMD_KEY_UP			(UART_CMD_KEY_DOWN	+1)
#define UART_CMD_KEY_CHANGE		(UART_CMD_KEY_UP	+1)
#define UART_CMD_BARVAL			(UART_CMD_KEY_CHANGE+1)
#define UART_CMD_PWR_SET		(UART_CMD_BARVAL	+1)
#define UART_CMD_FREQ			(UART_CMD_PWR_SET	+1)
#define UART_CMD_LED_LIGHT		(UART_CMD_FREQ		+1)
#define UART_CMD_LED_DARK		(UART_CMD_LED_LIGHT	+1)
#define UART_CMD_LED_GLITTER	(UART_CMD_LED_DARK	+1)
#define UART_CMD_GET_PWR_SET	(UART_CMD_LED_GLITTER+1)
#define UART_CMD_GET_BARVAL		(UART_CMD_GET_PWR_SET+1)
#define UART_CMD_GET_FREQ		(UART_CMD_GET_BARVAL+1)

#define UART_CMD_PAR_KEY_UP		KEY_UP
#define UART_CMD_PAR_KEY_DOWN	KEY_DOWN
#define UART_CMD_PAR_KEY_RESET	KEY_RESET
#define UART_CMD_PAR_KEY_TEST	KEY_TEST
#define UART_CMD_PAR_LED_RED	0X01
#define UART_CMD_PAR_LED_GREEN	0X02 */


void InitUart();
void InitUart2();
BYTE Receive1(BYTE* buf, BYTE len);
void Send1(BYTE* buf, BYTE len);
void Send2(BYTE* buf, BYTE len,BYTE channel);
void delay(char a);


#endif